// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitGuardAPI.Data;

#nullable disable

namespace OrbitGuard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602200219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AbrigoEntity", b =>
                {
                    b.Property<long>("IdAbrigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ABRIGO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAbrigo"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasDefaultValue("S")
                        .HasColumnName("ATIVO");

                    b.Property<int>("CapacidadeOcupada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("CAPACIDADE_OCUPADA");

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACIDADE_TOTAL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ENDERECO");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NOME");

                    b.HasKey("IdAbrigo");

                    b.HasIndex("IdRegiao");

                    b.ToTable("OG_ABRIGO", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AlertaEntity", b =>
                {
                    b.Property<long>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAlerta"));

                    b.Property<DateTime>("DataAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long?>("IdHistorico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_HISTORICO");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<string>("StatusAlerta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("ABERTO")
                        .HasColumnName("STATUS_ALERTA");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("TITULO");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdHistorico");

                    b.HasIndex("IdRegiao", "StatusAlerta")
                        .HasDatabaseName("IX_OG_ALERTA_REGIAO_STATUS");

                    b.ToTable("OG_ALERTA_RISCO", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AuditoriaAlertaEntity", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_AUDITORIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ACAO");

                    b.Property<DateTime>("DataAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AUDITORIA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("IdAlerta")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_ANTERIOR");

                    b.Property<string>("StatusNovo")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_NOVO");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdAlerta");

                    b.ToTable("OG_AUDITORIA_ALERTA", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.FonteEntity", b =>
                {
                    b.Property<long>("IdFonte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_FONTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFonte"));

                    b.Property<DateTime>("DataColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_COLETA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME");

                    b.Property<string>("PayloadExemplo")
                        .HasColumnType("CLOB")
                        .HasColumnName("PAYLOAD_EXEMPLO");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("TIPO_DADO");

                    b.Property<string>("UrlBase")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("URL_BASE");

                    b.HasKey("IdFonte");

                    b.ToTable("OG_FONTE_ESPACIAL", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.HistoricoEntity", b =>
                {
                    b.Property<long>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_HISTORICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdHistorico"));

                    b.Property<DateTime>("DataCalculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CALCULO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<decimal>("IndiceRisco")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("INDICE_RISCO");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("MOTIVO");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL_RISCO");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdRegiao");

                    b.ToTable("OG_HISTORICO_RISCO", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.LeituraEntity", b =>
                {
                    b.Property<long>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLeitura"));

                    b.Property<DateTime>("DataLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("IdSensor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("IOT")
                        .HasColumnName("ORIGEM");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdSensor", "DataLeitura")
                        .HasDatabaseName("IX_OG_LEITURA_SENSOR_DATA");

                    b.ToTable("OG_LEITURA_SENSOR", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.OcorrenciaEntity", b =>
                {
                    b.Property<long>("IdOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdOcorrencia"));

                    b.Property<DateTime>("DataOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_OCORRENCIA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long?>("IdAlerta")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("StatusOcorrencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("ABERTA")
                        .HasColumnName("STATUS_OCORRENCIA");

                    b.Property<string>("TipoOcorrencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_OCORRENCIA");

                    b.HasKey("IdOcorrencia");

                    b.HasIndex("IdAlerta");

                    b.HasIndex("IdRegiao")
                        .HasDatabaseName("IX_OG_OCORRENCIA_REGIAO");

                    b.HasIndex("IdUsuario");

                    b.ToTable("OG_OCORRENCIA", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.RecursoAbrigoEntity", b =>
                {
                    b.Property<long>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RECURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecurso"));

                    b.Property<long>("IdAbrigo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ABRIGO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("TIPO_RECURSO");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE");

                    b.HasKey("IdRecurso");

                    b.HasIndex("IdAbrigo");

                    b.ToTable("OG_RECURSO_ABRIGO", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.RegiaoEntity", b =>
                {
                    b.Property<long>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRegiao"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("CIDADE");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("PopulacaoEstimada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("POPULACAO_ESTIMADA");

                    b.Property<string>("TipoRiscoBase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_RISCO_BASE");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("UF");

                    b.HasKey("IdRegiao");

                    b.ToTable("OG_REGIAO_MONITORADA", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.SensorEntity", b =>
                {
                    b.Property<long>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSensor"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime>("DataInstalacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INSTALACAO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("StatusSensor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("STATUS_SENSOR");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_SENSOR");

                    b.HasKey("IdSensor");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UK_OG_SENSOR_CODIGO");

                    b.HasIndex("IdRegiao")
                        .HasDatabaseName("IX_OG_SENSOR_REGIAO");

                    b.ToTable("OG_SENSOR_IOT", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.UsuarioEntity", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasDefaultValue("S")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PERFIL");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_OG_USUARIO_EMAIL");

                    b.ToTable("OG_USUARIO", (string)null);
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AbrigoEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.RegiaoEntity", "Regiao")
                        .WithMany("Abrigos")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AlertaEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.HistoricoEntity", "Historico")
                        .WithMany("Alertas")
                        .HasForeignKey("IdHistorico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrbitGuardAPI.Entitys.RegiaoEntity", "Regiao")
                        .WithMany("AlertasRisco")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Historico");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AuditoriaAlertaEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.AlertaEntity", "Alerta")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdAlerta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.HistoricoEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.RegiaoEntity", "Regiao")
                        .WithMany("HistoricosRisco")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.LeituraEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.SensorEntity", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.OcorrenciaEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.AlertaEntity", "Alerta")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdAlerta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrbitGuardAPI.Entitys.RegiaoEntity", "Regiao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitGuardAPI.Entitys.UsuarioEntity", "Usuario")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.RecursoAbrigoEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.AbrigoEntity", "Abrigo")
                        .WithMany("Recursos")
                        .HasForeignKey("IdAbrigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abrigo");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.SensorEntity", b =>
                {
                    b.HasOne("OrbitGuardAPI.Entitys.RegiaoEntity", "Regiao")
                        .WithMany("Sensores")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AbrigoEntity", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.AlertaEntity", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.HistoricoEntity", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.RegiaoEntity", b =>
                {
                    b.Navigation("Abrigos");

                    b.Navigation("AlertasRisco");

                    b.Navigation("HistoricosRisco");

                    b.Navigation("Ocorrencias");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.SensorEntity", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("OrbitGuardAPI.Entitys.UsuarioEntity", b =>
                {
                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
